from datetime import datetime

def build_header():
    date_str = datetime.now().strftime("%d %B %Y")
    return f"""
📊 MarketToday
Simple. Calm. Indian Markets.

🗓 Date: {date_str}
━━━━━━━━━━━━━━━━━━━━━━
"""

def build_footer():
    return """
━━━━━━━━━━━━━━━━━━━━━━
ℹ️ Educational purpose only.
Not investment advice. No buy/sell calls.

🇮🇳 Indian stock market context only.
🤖 Generated by MarketToday AI
"""
    
def build_final_message(ai_content):
    return build_header() + ai_content.strip() + build_footer()
